services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php:8.1-apache
    container_name: app
    restart: unless-stopped
    ports:
      - 8000:80 
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker-compose/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker-compose/apache/vhosts.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - app-network

  db:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: commerce
    volumes:
      - ./docker-compose/mongo/data:/data/db
      - ./docker-compose/mongo/init:/docker-entrypoint-initdb.d
    networks:
      - app-network


networks:
  app-network:
    driver: bridge