services:

  db:
    image: mysql:9.2.0
    container_name: db
    restart: unless-stopped
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - c:\mysqldata:/var/lib/mysql
